name: bigbluebuttonsdk
description: "A new Flutter project."
version: 0.0.3
homepage:

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  web_socket_channel: ^3.0.3
  flutter_webrtc: ^1.1.0
#  flutter_webrtc_plus: ^0.11.2+7
  file_picker: ^10.3.2
#  speech_to_text: ^7.2.0
  get: ^4.7.2
  dio: ^5.9.0
#  flutter_background: ^1.3.0+1
#  flutter_background:
#    path: ../flutter_background
#  flutter_background_service: ^5.1.0
  screen_capturer: ^0.2.3
  flutter_local_notifications: ^19.4.0
  device_info_plus: ^11.5.0
  plugin_platform_interface: ^2.1.8
  socket_io_client: ^3.1.2
  flutter_svg: ^2.2.0
  phosphor_flutter: ^2.1.0
  permission_handler: ^12.0.1
  motion_toast: ^2.14.0
  toast: ^0.3.0
  flutter_sound: ^9.28.0
  record: ^6.1.1
  path_provider: ^2.1.5
#  google_speech: ^5.3.0  # For cloud speech recognition
#  speech_to_text: ^7.3.0
#  speech_to_text:
#    path: ../speech_to_text/speech_to_text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.bigbluebutton.bigbluebuttonsdk
        pluginClass: BigbluebuttonsdkPlugin
      ios:
        pluginClass: BigbluebuttonsdkPlugin
      linux:
        pluginClass: BigbluebuttonsdkPlugin
      macos:
        pluginClass: BigbluebuttonsdkPlugin
      windows:
        pluginClass: BigbluebuttonsdkPluginCApi
      web:
        pluginClass: BigbluebuttonsdkWeb
        fileName: bigbluebuttonsdk_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
